wandb_version: 1

batch_size:
  value: 254
epochs:
  value: 4
lr:
  value: 0.001383092686616943
lr_decay_step:
  value: 35
optimizer:
  value: Adam
seed:
  value: 42
val_ratio:
  value: 0.10034464997054404
valid_batch_size:
  value: 293
