wandb_version: 1

batch_size:
  value: 210
epochs:
  value: 3
lr:
  value: 0.0008671999288876595
lr_decay_step:
  value: 17
optimizer:
  value: Adam
seed:
  value: 57
val_ratio:
  value: 0.187994941362483
valid_batch_size:
  value: 397
