wandb_version: 1

batch_size:
  value: 104
epochs:
  value: 6
lr:
  value: 0.001728178501723711
lr_decay_step:
  value: 23
optimizer:
  value: SGD
seed:
  value: 80
val_ratio:
  value: 0.13477480081560964
valid_batch_size:
  value: 390
