wandb_version: 1

batch_size:
  value: 100
epochs:
  value: 5
lr:
  value: 0.001525565489596012
lr_decay_step:
  value: 27
optimizer:
  value: Adam
seed:
  value: 36
val_ratio:
  value: 0.10044932997491723
valid_batch_size:
  value: 305
