wandb_version: 1

batch_size:
  value: 159
epochs:
  value: 4
lr:
  value: 0.001364556126822063
lr_decay_step:
  value: 32
optimizer:
  value: Adam
seed:
  value: 59
val_ratio:
  value: 0.12052169678077902
valid_batch_size:
  value: 331
