wandb_version: 1

batch_size:
  value: 117
epochs:
  value: 3
lr:
  value: 0.0014273828234415615
lr_decay_step:
  value: 20
optimizer:
  value: SGD
seed:
  value: 57
val_ratio:
  value: 0.29549555441557807
valid_batch_size:
  value: 379
