wandb_version: 1

batch_size:
  value: 172
epochs:
  value: 6
lr:
  value: 0.0017134548145236515
lr_decay_step:
  value: 21
optimizer:
  value: SGD
seed:
  value: 75
val_ratio:
  value: 0.2195369174684312
valid_batch_size:
  value: 249
