wandb_version: 1

batch_size:
  value: 230
epochs:
  value: 8
lr:
  value: 0.001274387653416947
lr_decay_step:
  value: 19
optimizer:
  value: SGD
seed:
  value: 57
val_ratio:
  value: 0.27735951165177963
valid_batch_size:
  value: 257
