wandb_version: 1

batch_size:
  value: 245
epochs:
  value: 4
lr:
  value: 0.0008620826680656017
lr_decay_step:
  value: 15
optimizer:
  value: SGD
seed:
  value: 67
val_ratio:
  value: 0.12697975171668235
valid_batch_size:
  value: 258
