wandb_version: 1

batch_size:
  value: 234
epochs:
  value: 7
lr:
  value: 0.001999058632328834
lr_decay_step:
  value: 36
optimizer:
  value: Adam
seed:
  value: 84
val_ratio:
  value: 0.2352521572536124
valid_batch_size:
  value: 399
