wandb_version: 1

batch_size:
  value: 245
epochs:
  value: 8
lr:
  value: 0.0015731120080189004
lr_decay_step:
  value: 16
optimizer:
  value: Adam
seed:
  value: 54
val_ratio:
  value: 0.2717667778525868
valid_batch_size:
  value: 319
