wandb_version: 1

batch_size:
  value: 213
epochs:
  value: 2
lr:
  value: 0.0005834054765800974
lr_decay_step:
  value: 39
optimizer:
  value: Adam
seed:
  value: 61
val_ratio:
  value: 0.2080258764769269
valid_batch_size:
  value: 260
