wandb_version: 1

batch_size:
  value: 153
epochs:
  value: 10
lr:
  value: 0.0007472530452469191
lr_decay_step:
  value: 14
optimizer:
  value: Adam
seed:
  value: 81
val_ratio:
  value: 0.11445430544963532
valid_batch_size:
  value: 226
