wandb_version: 1

batch_size:
  value: 236
epochs:
  value: 3
lr:
  value: 0.0013689905758611602
lr_decay_step:
  value: 17
optimizer:
  value: SGD
seed:
  value: 50
val_ratio:
  value: 0.2474154969151273
valid_batch_size:
  value: 212
