wandb_version: 1

batch_size:
  value: 163
epochs:
  value: 4
lr:
  value: 0.0008826842377415401
lr_decay_step:
  value: 33
optimizer:
  value: SGD
seed:
  value: 64
val_ratio:
  value: 0.26738176397816993
valid_batch_size:
  value: 249
