wandb_version: 1

batch_size:
  value: 150
epochs:
  value: 7
lr:
  value: 0.0006478108636851973
lr_decay_step:
  value: 39
optimizer:
  value: Adam
seed:
  value: 39
val_ratio:
  value: 0.24313927843039193
valid_batch_size:
  value: 275
