wandb_version: 1

batch_size:
  value: 249
epochs:
  value: 5
lr:
  value: 0.0007015302270815019
lr_decay_step:
  value: 25
optimizer:
  value: SGD
seed:
  value: 61
val_ratio:
  value: 0.2240394410938874
valid_batch_size:
  value: 318
