wandb_version: 1

batch_size:
  value: 115
epochs:
  value: 10
lr:
  value: 0.0013341949348331552
lr_decay_step:
  value: 13
optimizer:
  value: SGD
seed:
  value: 58
val_ratio:
  value: 0.21827151878335335
valid_batch_size:
  value: 249
