wandb_version: 1

batch_size:
  value: 112
epochs:
  value: 3
lr:
  value: 0.0010815430745441583
lr_decay_step:
  value: 27
optimizer:
  value: Adam
seed:
  value: 24
val_ratio:
  value: 0.2352539345182131
valid_batch_size:
  value: 340
