wandb_version: 1

batch_size:
  value: 116
epochs:
  value: 30
lr:
  value: 0.0012604133937458644
lr_decay_step:
  value: 31
optimizer:
  value: Adam
seed:
  value: 59
val_ratio:
  value: 0.23696569248651408
valid_batch_size:
  value: 341
