wandb_version: 1

batch_size:
  value: 220
epochs:
  value: 30
lr:
  value: 0.0012081261695089148
lr_decay_step:
  value: 40
optimizer:
  value: SGD
seed:
  value: 82
val_ratio:
  value: 0.20708508030941877
valid_batch_size:
  value: 270
