wandb_version: 1

batch_size:
  value: 163
epochs:
  value: 30
lr:
  value: 0.0007418876714003951
lr_decay_step:
  value: 31
optimizer:
  value: Adam
seed:
  value: 28
val_ratio:
  value: 0.2034413376306699
valid_batch_size:
  value: 211
