wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1646275196
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 16
      - 17
      4: 3.8.5
      5: 0.12.10
      8:
      - 5
augmentation:
  desc: null
  value: CustomAugmentation
batch_size:
  desc: null
  value: 228
criterion:
  desc: null
  value: cross_entropy
data_dir:
  desc: null
  value: /opt/ml/input/data/train/images
dataset:
  desc: null
  value: MaskSplitByProfileDataset
epochs:
  desc: null
  value: 30
label:
  desc: null
  value: multi
learning_rate:
  desc: null
  value: 0.001
log_interval:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.0015027472203106534
lr_decay_step:
  desc: null
  value: 30
model:
  desc: null
  value: BaseModel
model_dir:
  desc: null
  value: ./model
model_param:
  desc: null
  value: resnet false
name:
  desc: null
  value: exp
optimizer:
  desc: null
  value: Adam
resize:
  desc: null
  value:
  - 224
  - 224
seed:
  desc: null
  value: 83
val_ratio:
  desc: null
  value: 0.1927111511425395
valid_batch_size:
  desc: null
  value: 271
weight_version:
  desc: null
  value: 0
