wandb_version: 1

batch_size:
  value: 247
epochs:
  value: 26
lr:
  value: 0.0019955023645964196
lr_decay_step:
  value: 13
optimizer:
  value: SGD
seed:
  value: 36
val_ratio:
  value: 0.18913656172169907
valid_batch_size:
  value: 324
