wandb_version: 1

batch_size:
  value: 154
epochs:
  value: 36
lr:
  value: 0.001740295444478017
lr_decay_step:
  value: 25
optimizer:
  value: Adam
seed:
  value: 81
val_ratio:
  value: 0.29313077024898093
valid_batch_size:
  value: 234
