wandb_version: 1

batch_size:
  value: 171
epochs:
  value: 30
lr:
  value: 0.0007795026545006879
lr_decay_step:
  value: 11
optimizer:
  value: SGD
seed:
  value: 35
val_ratio:
  value: 0.3635261446602809
valid_batch_size:
  value: 357
