wandb_version: 1

batch_size:
  value: 213
epochs:
  value: 30
lr:
  value: 0.001071412529729475
lr_decay_step:
  value: 18
optimizer:
  value: SGD
seed:
  value: 44
val_ratio:
  value: 0.23111780584806116
valid_batch_size:
  value: 242
