wandb_version: 1

batch_size:
  value: 220
epochs:
  value: 30
lr:
  value: 0.0005382039921783819
lr_decay_step:
  value: 40
optimizer:
  value: Adam
seed:
  value: 48
val_ratio:
  value: 0.21377684055054597
valid_batch_size:
  value: 191
