wandb_version: 1

batch_size:
  value: 188
epochs:
  value: 30
lr:
  value: 0.001753316580325902
lr_decay_step:
  value: 34
optimizer:
  value: Adam
seed:
  value: 29
val_ratio:
  value: 0.130983010431603
valid_batch_size:
  value: 137
