wandb_version: 1

batch_size:
  value: 140
epochs:
  value: 30
lr:
  value: 0.0015714668010743716
lr_decay_step:
  value: 11
optimizer:
  value: Adam
seed:
  value: 40
val_ratio:
  value: 0.11087953174472136
valid_batch_size:
  value: 176
