wandb_version: 1

batch_size:
  value: 140
epochs:
  value: 30
lr:
  value: 0.0007724717924589509
lr_decay_step:
  value: 37
optimizer:
  value: SGD
seed:
  value: 29
val_ratio:
  value: 0.12559742205163008
valid_batch_size:
  value: 137
