wandb_version: 1

batch_size:
  value: 174
epochs:
  value: 30
lr:
  value: 0.001583453373367758
lr_decay_step:
  value: 28
optimizer:
  value: Adam
seed:
  value: 36
val_ratio:
  value: 0.15587463150039274
valid_batch_size:
  value: 114
