wandb_version: 1

batch_size:
  value: 177
epochs:
  value: 30
lr:
  value: 0.0009653217463164448
lr_decay_step:
  value: 15
optimizer:
  value: SGD
seed:
  value: 25
val_ratio:
  value: 0.2671583879717258
valid_batch_size:
  value: 104
