wandb_version: 1

batch_size:
  value: 197
epochs:
  value: 30
lr:
  value: 0.0016578977879614608
lr_decay_step:
  value: 22
optimizer:
  value: SGD
seed:
  value: 63
val_ratio:
  value: 0.19389238563241823
valid_batch_size:
  value: 253
