wandb_version: 1

batch_size:
  value: 171
epochs:
  value: 30
lr:
  value: 0.0010104500650141824
lr_decay_step:
  value: 34
optimizer:
  value: Adam
seed:
  value: 67
val_ratio:
  value: 0.12468016313049364
valid_batch_size:
  value: 298
