wandb_version: 1

batch_size:
  value: 136
epochs:
  value: 30
lr:
  value: 0.001342152930056229
lr_decay_step:
  value: 31
optimizer:
  value: Adam
seed:
  value: 57
val_ratio:
  value: 0.3786810837441767
valid_batch_size:
  value: 331
