wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1646280438
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      - 16
      4: 3.8.5
      5: 0.12.10
      8:
      - 5
batch_size:
  desc: null
  value: 254
epochs:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.001
lr:
  desc: null
  value: 0.001383092686616943
lr_decay_step:
  desc: null
  value: 35
optimizer:
  desc: null
  value: Adam
seed:
  desc: null
  value: 42
val_ratio:
  desc: null
  value: 0.10034464997054404
valid_batch_size:
  desc: null
  value: 293
